name: fun_flutter_kit_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# 开启自动生成json
flutter-json:
  enable:true

dependencies:
  flutter:
    sdk: flutter
  # lib
  fun_flutter_kit:
    path: ../

  # helpers
  dio: ^4.0.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # - assets/animations/
    - assets/images/


