name: fun_flutter_kit
description: A fun development kit with flutter
version: 0.0.3
homepage: https://github.com/phoenixsky
repository: https://github.com/phoenixsky/fun_flutter_kit

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  pull_to_refresh: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


